spring:
  datasource:
    url: jdbc:postgresql://db:5432/project1
    username: postgres
    password: <your-database-password>
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: <your-rabbitmq-password>
    exchange: overdue_books_exchange
    routing-key: book.overdue
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true  # Enable for development only, consider disabling for production
  mail:
    host: smtp.gmail.com
    port: 587
    username: <your-email>
    password: <your-email-password>  # Use environment variables for better security
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
