spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    exchange: ${RABBITMQ_EXCHANGE}
    routing-key: ${RABBITMQ_ROUTING_KEY}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT }
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

stripe:
  publishable-key: ${STRIPE_PUBLISHABLE_KEY}
  secret-key: ${STRIPE_SECRET_KEY}
  currency: ${STRIPE_CURRENCY}
